//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnualidadCronogramaPagos
    {
        public int ID { get; set; }
        public int Cliente_ID { get; set; }
        public int Credito_ID { get; set; }
        public int Periodo { get; set; }
        public decimal Cuota { get; set; }
        public bool EstadoPago { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Creditos Creditos { get; set; }
    }
}
