//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creditos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Creditos()
        {
            this.AnualidadCronogramaPagos = new HashSet<AnualidadCronogramaPagos>();
            this.CreditoValorFuturo = new HashSet<CreditoValorFuturo>();
        }
    
        public int ID { get; set; }
        public int Cliente_ID { get; set; }
        public int Tienda_ID { get; set; }
        public string TipoCredito { get; set; }
        public decimal MontoCredito { get; set; }
        public int Plazo { get; set; }
        public decimal TEA { get; set; }
        public decimal TasaMora { get; set; }
        public System.DateTime FechaCompra { get; set; }
        public Nullable<System.DateTime> FechaPago { get; set; }
        public Nullable<decimal> PagoFinal { get; set; }
        public Nullable<decimal> Interes { get; set; }
        public string TipoGracia { get; set; }
        public int DiasGracia { get; set; }
        public bool EstadoPago { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnualidadCronogramaPagos> AnualidadCronogramaPagos { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Tienda Tienda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditoValorFuturo> CreditoValorFuturo { get; set; }
    }
}
