//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class TiendaCliente
    {
        public int ID { get; set; }
        public int Cliente_ID { get; set; }
        public int Tienda_ID { get; set; }
        public string NombresCliente { get; set; }
        public bool EstadoCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Tienda Tienda { get; set; }
    }
}
